const sujetos = {
    // 6TO GRADO
    "ana_6": { nombre: "Ana", cumple: "---", tlf: "---", ig: "---", ig_st: "---", tt: "---", tt_st: "---", rb: "---", nota: "Archivo 6to" },
    "samuel_6": { nombre: "Samuel", cumple: "---", tlf: "---", ig: "---", ig_st: "---", tt: "---", tt_st: "---", rb: "---", nota: "Archivo 6to" },
    "wuender_6": { nombre: "Wuender", cumple: "---", tlf: "---", ig: "---", ig_st: "---", tt: "---", tt_st: "---", rb: "---", nota: "Archivo 6to" },
    "santiago_b_6": { nombre: "Santiago B.", cumple: "---", tlf: "---", ig: "---", ig_st: "---", tt: "---", tt_st: "---", rb: "---", nota: "Archivo 6to" },
    "emiliana_6": { nombre: "Emiliana", cumple: "---", tlf: "---", ig: "---", ig_st: "---", tt: "---", tt_st: "---", rb: "---", nota: "Archivo 6to" },
    "andres_6": { nombre: "Andrés", cumple: "---", tlf: "---", ig: "---", ig_st: "---", tt: "---", tt_st: "---", rb: "---", nota: "Archivo 6to" },
    "misael_6": { nombre: "Misael", cumple: "---", tlf: "---", ig: "---", ig_st: "---", tt: "---", tt_st: "---", rb: "---", nota: "Archivo 6to" },
    "matias_6": { nombre: "Matias", cumple: "---", tlf: "---", ig: "---", ig_st: "---", tt: "---", tt_st: "---", rb: "---", nota: "Archivo 6to" },
    "alexa_6": { nombre: "Alexa", cumple: "---", tlf: "---", ig: "---", ig_st: "---", tt: "---", tt_st: "---", rb: "---", nota: "Archivo 6to" },
    "luis_6": { nombre: "Luis", cumple: "---", tlf: "---", ig: "---", ig_st: "---", tt: "---", tt_st: "---", rb: "---", nota: "Archivo 6to" },
    "josue_6": { nombre: "Josué", cumple: "---", tlf: "---", ig: "---", ig_st: "---", tt: "---", tt_st: "---", rb: "---", nota: "Archivo 6to" },
    "mauricio_v_6": { nombre: "Mauricio", cumple: "---", tlf: "---", ig: "---", ig_st: "---", tt: "---", tt_st: "---", rb: "---", nota: "Investigación en curso" },
    "yuliannys_6": { nombre: "Yuliannys", cumple: "---", tlf: "---", ig: "---", ig_st: "---", tt: "---", tt_st: "---", rb: "---", nota: "Archivo 6to" },
    "isabella_6": { nombre: "Isabella", cumple: "---", tlf: "---", ig: "---", ig_st: "---", tt: "---", tt_st: "---", rb: "---", nota: "Archivo 6to" },
    "alexandra_6": { nombre: "Alexandra", cumple: "---", tlf: "---", ig: "---", ig_st: "---", tt: "---", tt_st: "---", rb: "---", nota: "Archivo 6to" },
    "antonella_6": { nombre: "Antonella", cumple: "---", tlf: "---", ig: "---", ig_st: "---", tt: "---", tt_st: "---", rb: "---", nota: "Archivo 6to" },
    "nehomar_6": { nombre: "Nehomar", cumple: "---", tlf: "---", ig: "---", ig_st: "---", tt: "---", tt_st: "---", rb: "---", nota: "Archivo 6to" },
    "adriana_6": { nombre: "Adriana", cumple: "---", tlf: "---", ig: "---", ig_st: "---", tt: "---", tt_st: "---", rb: "---", nota: "Archivo 6to" },
    "victoria_m_6": { nombre: "Victoria M", cumple: "---", tlf: "---", ig: "---", ig_st: "---", tt: "---", tt_st: "---", rb: "---", nota: "Archivo 6to" },
    "vivianne_6": { nombre: "Vivianne", cumple: "---", tlf: "---", ig: "---", ig_st: "---", tt: "---", tt_st: "---", rb: "---", nota: "Archivo 6to" },
    "dannymar_6": { nombre: "Dannymar", cumple: "---", tlf: "---", ig: "---", ig_st: "---", tt: "---", tt_st: "---", rb: "---", nota: "Archivo 6to" },
    "juan_6": { nombre: "Juan", cumple: "---", tlf: "---", ig: "---", ig_st: "---", tt: "---", tt_st: "---", rb: "---", nota: "Archivo 6to" },
    "lucia_r": { nombre: "Lucía Rios", cumple: "---", tlf: "---", ig: "---", ig_st: "---", tt: "---", tt_st: "---", rb: "---", nota: "Investigación en curso" },
    "gael_6": { nombre: "Gael", cumple: "---", tlf: "---", ig: "---", ig_st: "---", tt: "---", tt_st: "---", rb: "---", nota: "Archivo 6to" },
    "santiago_v_6": { nombre: "Santiago V.", cumple: "---", tlf: "---", ig: "---", ig_st: "---", tt: "---", tt_st: "---", rb: "---", nota: "Archivo 6to" },
    "enrique_6": { nombre: "Enrique", cumple: "---", tlf: "---", ig: "---", ig_st: "---", tt: "---", tt_st: "---", rb: "---", nota: "Archivo 6to" },

    // BACHILLERATO REPETIDOS Y NUEVOS
    "abdias_v": { nombre: "Abdias Vicent", cumple: "---", tlf: "---", ig: "---", ig_st: "---", tt: "---", tt_st: "---", rb: "---", nota: "Estudiante de 1ro y 2do" },
    "alejandra_o": { nombre: "Alejandra Osuna", cumple: "---", tlf: "---", ig: "---", ig_st: "---", tt: "---", tt_st: "---", rb: "---", nota: "Estudiante de 1ro y 2do" },
    "alondra_c": { nombre: "Alondra Castillo", cumple: "---", tlf: "---", ig: "---", ig_st: "---", tt: "---", tt_st: "---", rb: "---", nota: "Estudiante de 1ro y 2do" },
    "camila_p": { nombre: "Camila Pereira", cumple: "---", tlf: "---", ig: "---", ig_st: "---", tt: "---", tt_st: "---", rb: "---", nota: "Estudiante de 1ro y 2do" },
    "constanza_c": { nombre: "Constanza Cabeza", cumple: "---", tlf: "---", ig: "---", ig_st: "---", tt: "---", tt_st: "---", rb: "---", nota: "Estudiante de 1ro y 2do" },
    "daniel_e": { nombre: "Daniel Escalona", cumple: "---", tlf: "---", ig: "---", ig_st: "---", tt: "---", tt_st: "---", rb: "---", nota: "Estudiante de 1ro y 2do" },
    "daniela_d": { nombre: "Daniela Dominguez", cumple: "---", tlf: "---", ig: "---", ig_st: "---", tt: "---", tt_st: "---", rb: "---", nota: "Estudiante de 1ro y 2do" },
    "david_v": { nombre: "David Velázquez", cumple: "---", tlf: "---", ig: "---", ig_st: "---", tt: "---", tt_st: "---", rb: "---", nota: "Estudiante de 1ro y 2do" },
    "fabianna_v": { nombre: "Fabianna Viloria", cumple: "---", tlf: "---", ig: "---", ig_st: "---", tt: "---", tt_st: "---", rb: "---", nota: "Estudiante de 1ro y 2do" },
    "genio_g": { nombre: "Genio García", cumple: "---", tlf: "---", ig: "---", ig_st: "---", tt: "---", tt_st: "---", rb: "---", nota: "Estudiante de 1ro y 2do" },
    "hector_r": { nombre: "Héctor Ruiz", cumple: "---", tlf: "---", ig: "---", ig_st: "---", tt: "---", tt_st: "---", rb: "---", nota: "Estudiante de 1ro y 2do" },
    "hector_v": { nombre: "Héctor Velázquez", cumple: "---", tlf: "---", ig: "---", ig_st: "---", tt: "---", tt_st: "---", rb: "---", nota: "Estudiante de 1ro y 2do" },
    "jadasa_m": { nombre: "Jadasa Mayz", cumple: "---", tlf: "---", ig: "---", ig_st: "---", tt: "---", tt_st: "---", rb: "---", nota: "Estudiante de 1ro y 2do" },
    "josnel_g": { nombre: "Josnel Guerra", cumple: "---", tlf: "---", ig: "---", ig_st: "---", tt: "---", tt_st: "---", rb: "---", nota: "Estudiante de 1ro y 2do" },
    "kaolineth_c": { nombre: "Kaolineth Castro", cumple: "---", tlf: "---", ig: "---", ig_st: "---", tt: "---", tt_st: "---", rb: "---", nota: "Estudiante de 1ro y 2do" },
    "luis_rene_p": { nombre: "Luís René Prado", cumple: "---", tlf: "---", ig: "---", ig_st: "---", tt: "---", tt_st: "---", rb: "---", nota: "Estudiante de 1ro y 2do" },
    "moises_g": { nombre: "Moisés Guerra", cumple: "---", tlf: "---", ig: "---", ig_st: "---", tt: "---", tt_st: "---", rb: "---", nota: "Estudiante de 1ro y 2do" },
    "paula_q": { nombre: "Paula Quijada - Mahi/Rain", cumple: "---", tlf: "---", ig: "---", ig_st: "---", tt: "---", tt_st: "---", rb: "---", nota: "Presente en múltiples archivos" },
    "ricardo_o": { nombre: "Ricardo Olivier", cumple: "---", tlf: "---", ig: "---", ig_st: "---", tt: "---", tt_st: "---", rb: "---", nota: "Estudiante de 1ro y 2do" },
    "santiago_q": { nombre: "Santiago Quijada", cumple: "---", tlf: "---", ig: "---", ig_st: "---", tt: "---", tt_st: "---", rb: "---", nota: "Solo 1er Año" },
    "adelybert_g": { nombre: "Adelybert González", cumple: "---", tlf: "---", ig: "---", ig_st: "---", tt: "---", tt_st: "---", rb: "---", nota: "Ingreso en 2do Año" },
    "luna_l": { nombre: "Luna López", cumple: "---", tlf: "---", ig: "---", ig_st: "---", tt: "---", tt_st: "---", rb: "---", nota: "Ingreso en 2do Año" },
    "mauricio_v": { nombre: "Mauricio Villasana", cumple: "---", tlf: "---", ig: "---", ig_st: "---", tt: "---", tt_st: "---", rb: "---", nota: "Solo 1er año" },
    // SOULSNOW FAMILY EXCLUSIVOS
    "jose_f": { nombre: "José Freites - Simo/John", cumple: "---", tlf: "---", ig: "---", ig_st: "---", tt: "---", tt_st: "---", rb: "---", nota: "Family" },
    "bubbly": { nombre: "Bubbly", cumple: "---", tlf: "---", ig: "---", ig_st: "---", tt: "---", tt_st: "---", rb: "---", nota: "Family" },
    "max_f": { nombre: "Max", cumple: "---", tlf: "---", ig: "---", ig_st: "---", tt: "---", tt_st: "---", rb: "---", nota: "Family" },
    "val_f": { nombre: "Val/Fan", cumple: "---", tlf: "---", ig: "---", ig_st: "---", tt: "---", tt_st: "---", rb: "---", nota: "Family" },
    "mayday_f": { nombre: "Mayday/Winter", cumple: "---", tlf: "---", ig: "---", ig_st: "---", tt: "---", tt_st: "---", rb: "---", nota: "Family" }
    "bal_f": { nombre: "Bal/Kyom", cumple: "---", tlf: "---", ig: "---", ig_st: "---", tt: "---", tt_st: "---", rb: "---", nota: "Family" }
};

const baseDeDatos = {
    "sexto_tigre": ["ana_6", "samuel_6", "wuender_6", "santiago_b_6", "emiliana_6", "andres_6", "misael_6", "matias_6", "alexa_6", "luis_6", "josue_6", "mauricio_v_6", "yuliannys_6", "isabella_6", "alexandra_6", "antonella_6", "nehomar_6", "adriana_6", "victoria_m_6", "vivianne_6", "dannymar_6", "juan_6", "lucia_r", "gael_6", "santiago_v_6", "enrique_6"],
    "primero_bello": ["abdias_v", "alejandra_o", "alondra_c", "camila_p", "constanza_c", "daniel_e", "daniela_d", "david_v", "fabianna_v", "genio_g", "hector_r", "hector_v", "jadasa_m", "josnel_g", "kaolineth_c", "lucia_r", "luis_rene_p", "moises_g", "mauricio_v", "paula_q", "ricardo_o", "santiago_q"],
    "segundo_bello": ["abdias_v", "alejandra_o", "alondra_c", "camila_p", "constanza_c", "daniel_e", "daniela_d", "david_v", "fabianna_v", "genio_g", "hector_r", "hector_v", "jadasa_m", "josnel_g", "kaolineth_c", "lucia_r", "luis_rene_p", "moises_g", "paula_q", "ricardo_o", "adelybert_g", "luna_l"],
    "soulsnow_family": ["paula_q", "jose_f", "bubbly", "max_f", "val_f", "mayday_f", "bal_f"]
};
